param([string]$RepoRoot="C:\projects\Unity\AegisRTS.FrameworkLab")
$ErrorActionPreference='Stop';Add-Type -AssemblyName System.IO.Compression.FileSystem;Add-Type -AssemblyName System.Drawing
$name='Infantry_Phase03_SecondaryForms_Review_v001';$parent=Join-Path $RepoRoot 'docs\ArtProduction\ReviewPackages';$root=Join-Path $parent $name;$man=Join-Path $root 'Manifests';$zip=Join-Path $parent ($name+'.zip')
$required=@('README.md','00_Phase03_Report.md','01_Geometry_Stats.md','02_Secondary_Form_Change_List.md','03_Material_ID_Plan.md','04_Unity_Review_Status.md','05_Open_Issues.md','06_Review_Checklist.md','07_Visual_Evidence_Index.md','Blender\CHR_Infantry_A_v004.blend','Manifests\P03_BUILD_RESULT.json','Manifests\Geometry_Summary.json','Manifests\Object_Manifest.csv','Manifests\Bone_Manifest.csv','Screenshots\Clay\01_Clay_Front.png','Screenshots\MaterialID\MaterialID_Front.png','Screenshots\Silhouette\Silhouette_Front.png','Screenshots\Wireframe\Wireframe_Front.png','Screenshots\Detail\Detail_Chest.png','Screenshots\Detail\Detail_Shield_Back.png','Screenshots\Comparison\L1_vs_v004_Front.png','Screenshots\Comparison\P02R1_vs_v004_Front.png','Screenshots\ScreenSize\Clay_64px.png','Screenshots\Unity\MANUAL_UNITY_REVIEW_REQUIRED.txt')
foreach($r in $required){if(-not(Test-Path -LiteralPath (Join-Path $root $r) -PathType Leaf)){throw "Missing required file: $r"}}
$shots=foreach($f in Get-ChildItem (Join-Path $root 'Screenshots') -Recurse -File -Filter '*.png'|Sort-Object FullName){$i=[Drawing.Image]::FromFile($f.FullName);try{[pscustomobject]@{Path=$f.FullName.Substring($root.Length+1).Replace('\','/');Width=$i.Width;Height=$i.Height;Bytes=$f.Length;SHA256=(Get-FileHash $f.FullName -Algorithm SHA256).Hash}}finally{$i.Dispose()}}
$shots|Export-Csv (Join-Path $man 'Screenshot_Manifest.csv') -NoTypeInformation -Encoding utf8
$fm=Join-Path $man 'File_Manifest.csv';$sums=Join-Path $man 'SHA256SUMS.txt';Remove-Item $fm,$sums -Force -ErrorAction SilentlyContinue
$rows=foreach($f in Get-ChildItem $root -Recurse -File|Sort-Object FullName){if($f.FullName -in @($fm,$sums)){continue};[pscustomobject]@{Path=$f.FullName.Substring($root.Length+1).Replace('\','/');Bytes=$f.Length;SHA256=(Get-FileHash $f.FullName -Algorithm SHA256).Hash}}
$rows|Export-Csv $fm -NoTypeInformation -Encoding utf8
$lines=foreach($f in Get-ChildItem $root -Recurse -File|Sort-Object FullName){if($f.FullName -eq $sums){continue};'{0} *{1}' -f (Get-FileHash $f.FullName -Algorithm SHA256).Hash,$f.FullName.Substring($root.Length+1).Replace('\','/')}
[IO.File]::WriteAllLines($sums,$lines,[Text.UTF8Encoding]::new($false))
$rr=[IO.Path]::GetFullPath($root);$rp=[IO.Path]::GetFullPath($parent);$rz=[IO.Path]::GetFullPath($zip);if(-not $rr.StartsWith($rp+[IO.Path]::DirectorySeparatorChar)){throw 'Unsafe package path'};if(-not $rz.StartsWith($rp+[IO.Path]::DirectorySeparatorChar)){throw 'Unsafe zip path'}
Remove-Item $rz -Force -ErrorAction SilentlyContinue;[IO.Compression.ZipFile]::CreateFromDirectory($rr,$rz,[IO.Compression.CompressionLevel]::Optimal,$true)
$folder=@{};Get-ChildItem $rr -Recurse -File|%{$folder[$_.FullName.Substring($rr.Length+1).Replace('\','/')]=(Get-FileHash $_.FullName -Algorithm SHA256).Hash}
$arc=[IO.Compression.ZipFile]::OpenRead($rz);try{$zmap=@{};foreach($e in $arc.Entries){if(!$e.Name){continue};$n=$e.FullName.Replace('\','/');$pre=$name+'/';if(!$n.StartsWith($pre)){throw "Unexpected ZIP root: $n"};$stream=$e.Open();try{$h=[Security.Cryptography.SHA256]::Create();try{$zmap[$n.Substring($pre.Length)]=[BitConverter]::ToString($h.ComputeHash($stream)).Replace('-','')}finally{$h.Dispose()}}finally{$stream.Dispose()}}}finally{$arc.Dispose()}
$missing=@($folder.Keys|?{-not $zmap.ContainsKey($_)});$extra=@($zmap.Keys|?{-not $folder.ContainsKey($_)});$bad=@($folder.Keys|?{$zmap.ContainsKey($_)-and$zmap[$_] -ne $folder[$_]});if($missing.Count+$extra.Count+$bad.Count){throw "ZIP mismatch missing=$($missing.Count) extra=$($extra.Count) hash=$($bad.Count)"}
[pscustomobject]@{Status='READY FOR PHASE03 REVIEW';Package=$rr;FolderFiles=$folder.Count;FolderBytes=(Get-ChildItem $rr -Recurse -File|Measure-Object Length -Sum).Sum;ScreenshotPngs=$shots.Count;Zip=$rz;ZipEntries=$zmap.Count;ZipBytes=(Get-Item $rz).Length;ZipSHA256=(Get-FileHash $rz -Algorithm SHA256).Hash;Missing=$missing.Count;Extra=$extra.Count;HashMismatch=$bad.Count}|ConvertTo-Json
